apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/df/dockerfile",
            "--context=dir://workspace",
            "--destination=<user-name>/<repo>"] # replace with your dockerhub account
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-storage
        mountPath: /df
      - name: imagedisk
        mountPath: /image
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    #Previusly created config map with the Dockerfile.
    - name: dockerfile-storage
      configMap:
        name: dockerfile
    - name: imagedisk
      configMap:
        name: dockerfile
      # persistentVolumeClaim:
      #   claimName: dockerfile-claim
    - name: imagedisk
      persistentVolumeClaim:
        claimName: kubenode
